@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

AddressBook *-right-> "1" UniqueMeetingList
AddressBook *-right-> "1" UniquePersonList
AddressBook *-right-> "1" UniqueTagList
UniqueTagList -[hidden]down- UniquePersonList
UniqueTagList -[hidden]down- UniquePersonList

UniqueTagList -right-> "*" Tag
UniquePersonList -right-> Person
UniqueMeetingList *-right-> Meeting

Person -up-> "*" Tag

Person *--> ID
Person *--> Name
Person *--> Phone
Person *--> Email

Meeting *-right-> "*" UUID
Meeting *--> "1" Date
Meeting *--> "1" Description
@enduml
