@startuml
!include style.puml
skinparam ArrowFontStyle plain
scale 3

title Edit Command

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":EditCommandParser" as EditCommandParser LOGIC_COLOR
participant "e:EditCommand" as EditCommand LOGIC_COLOR
participant ":EditPersonDescriptor" as EditPersonDescriptor LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute( \n "edit 1 n/john p/99999999")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand(\n "edit 1 n/john p/99999999")
activate AddressBookParser

create EditCommandParser
AddressBookParser -> EditCommandParser
activate EditCommandParser

EditCommandParser -> AddressBookParser
deactivate

AddressBookParser -> EditCommandParser: parse("1 n/john p/99999999")
activate EditCommandParser

create EditPersonDescriptor

note right of EditPersonDescriptor
EditPersonDescriptor is a
nested class within EditCommand.
end note

EditCommandParser -> EditPersonDescriptor
activate EditPersonDescriptor
return

EditCommandParser -> EditPersonDescriptor : Populate fields
activate EditPersonDescriptor
return

create EditCommand
EditCommandParser -> EditCommand
activate EditCommand
EditCommand --> EditCommandParser : e
deactivate EditCommand

EditCommandParser --> AddressBookParser : e
deactivate EditCommandParser

'Hidden arrow to position the destroy marker below the end of the activation bar.
EditCommandParser -[hidden]-> AddressBookParser
destroy EditCommandParser

AddressBookParser --> LogicManager : e
deactivate AddressBookParser

LogicManager -> EditCommand : execute(m)
activate EditCommand

EditCommand -> EditPersonDescriptor : Get fields to edit
activate EditPersonDescriptor
EditPersonDescriptor --> EditCommand
deactivate EditPersonDescriptor

EditCommand -> Model : editPerson(personToEdit, editedPerson)
activate Model
Model --> EditCommand
deactivate Model

create CommandResult
EditCommand -> CommandResult
activate CommandResult
CommandResult --> EditCommand : r
deactivate CommandResult

EditCommand --> LogicManager : r

[<--LogicManager : r
deactivate LogicManager
@enduml
